#!/usr/bin/env node

function read(file) {
    let content = require('fs').readFileSync(file, 'utf8')
    return content.split('\n').filter(Boolean)
}

function log(...args) {
    console.log(...args)
}

function processLine(line) {
    return line.split('')
}

let lines = read('3-input').map(processLine)

// log('lines', lines)

function get(x, y) {
    let line = lines[y]
    if (line === undefined) {
        return null
    }
    let width = line.length
    return line[x % width]
}

function count(xd, yd) {
    let x = 0
    let y = 0
    let n = 0
    while (true) {
        let got = get(x, y)
        if (got === null) {
            return n
        }
        if (got === '#') {
            n++
        }
        x += xd
        y += yd
    }
}

log(count(1, 1)
    * count(3, 1)
    * count(5, 1)
    * count(7, 1)
    * count(1, 2)
)
