#!/usr/bin/env node

function read(file) {
    let content = require('fs').readFileSync(file, 'utf8')
    return content.split('\n').filter(Boolean)
}

function log(...args) {
    console.log(...args)
}

let lines = read('1-input')
