#!/usr/bin/env node

function read(file) {
	let content = require('fs').readFileSync(file, 'utf8')
	return content.split('\n').filter(Boolean)
}

function log(...args) {
	console.log(...args)
}

function process(line) {
	return line.replace(/./g, (x) => {
		return {
			F: 0,
			B: 1,
			L: 0,
			R: 1,
		}[x]
	})
}

let lines = read('5-input').map(process)
let nums = lines.map((line) => Number('0b' + line))
log(Math.max(...nums))

nums.sort((a, b) => a - b)

// log(nums)
for (let i = 0; i < nums.length; i++) {
	if (nums[i] + 1 !== nums[i + 1]) {
		log('missing', nums[i] + 1)
	}
}
