#!/usr/bin/env node

function read(file) {
    let content = require('fs').readFileSync(file, 'utf8')
    return content.split('\n\n').map(x => x.split('\n').filter(Boolean))
}

function log(...args) {
    console.log(...args)
}

let groups = read('6-input')
// let groups = read('6-test')
log(groups)

function sum(group) {
    let letters = 'abcdefghijklmnopqrstuvwxyz'
    let all = new Set(letters.split(''))
    for (let person of group) {
        let answers = [...person]
        for (let letter of letters) {
            if (!answers.includes(letter)) {
                all.delete(letter)
            }
        }
    }

    // 3510 too low
    log('set', all)
    return all.size
}

let total = 0
for (let group of groups) {
    total += sum(group)
}

log(total)
