#!/usr/bin/env node

function read(file) {
	let content = require('fs').readFileSync(file, 'utf8')
	return content.split('\n').filter(Boolean).map(Number)
}

function log(...args) {
	console.log(...args)
}

let day = process.argv[1].substr(-1)
// let lines = read(`${day}-test`)
let lines = read(`${day}-input`)

log(lines)
